name: flutter_wallet
description: Flutter plugin to add pkpass to iOS wallet (Passbook)
version: 0.0.4
homepage: https://github.com/vico-aguado/flutter_wallet

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.vicoaguado.flutter_wallet
        pluginClass: FlutterWalletPlugin
      ios:
        pluginClass: FlutterWalletPlugin
